### ISSUE TITLE
bug number to String error

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1089]
1461225923504726020.00 
- it data type  number in rhion 
- it data type  Double in Java
```
let x = 1461225923504726020.00;
x.toString();
```
!!Precision is not enough

**Comment by p-bakker** [comment]
Read up on numbers in JavaScript

**Comment by MikeGrateful** [comment]
I queried the data from the database using json.parse 。 json.parse Does not support BIGINT

**Comment by tonygermano** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

Integer values larger than that should be stored as strings in json to avoid precision loss. The string can be converted to a bigint after parsing, but typically in cases like this where it is just an identifier, there is no need since you won't be doing any calculations on it or any comparisons except maybe equality.

**Comment by MikeGrateful** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
> 
> Integer values larger than that should be stored as strings in json to avoid precision loss. The string can be converted to a bigint after parsing, but typically in cases like this where it is just an identifier, there is no need since you won't be doing any calculations on it or any comparisons except maybe equality.

TQMH
I changed the code and recompiled it

![image](https://user-images.githubusercontent.com/15280143/142673056-0ec7e491-6ee7-4080-8d56-efbcb69cba90.png)

**Comment by tonygermano** [comment]
That's great if that works for you.

https://datatracker.ietf.org/doc/html/rfc8259#section-6
The JSON spec clearly spells out what it allowed for numbers, and specifically warns:
> This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754 binary64 (double precision) numbers [IEEE754] is generally
   available and widely used, good interoperability can be achieved by
   implementations that expect no more precision or range than these
   provide, in the sense that implementations will approximate JSON
   numbers within the expected precision.  A JSON number such as 1E400
   or 3.141592653589793238462643383279 may indicate potential
   interoperability problems, since it suggests that the software that
   created it expects receiving software to have greater capabilities
   for numeric magnitude and precision than is widely available.
>
>   Note that when such software is used, numbers that are integers and
   are in the range [-(2^53)+1, (2^53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.

This is why it's usually a good idea to convert integers to strings before encoding them as json if they will potentially go outside of that interoperable range.
