### ISSUE TITLE
Number gets convert to double without optimizations

### ISSUE THREAD

**Issue by esfomeado** [mozilla/rhino#1202]
Hello,

For instance let's assume I have the following JSON among other JavaScript code.

```
{
    key: [1234]
}
```

Without any optimizations the value of the key will be a 1.234 and of the type double and if I turn on the optimizations it will have the value 1234 and the type int which is correct.

Why there is this different behavior and how can I force It to be int.

Thanks

**Comment by p-bakker** [comment]
Can't realy comment on the substance of your question, but I can tell you that in order to increase the likelyhood you'll get an answer, you should provide more info, like which optimizations are you turning on/off and how are you interacting with this JSON object and determining whether its a int of a double.

Best to provide samplecode reproducing the problem

**Comment by esfomeado** [comment]
I'm setting the optimization level to 0.

I really don't interreact with the JSON.

I just call the `context.evaluateString` and then I just check the value of the `NativeObject` and I see it's a double/int.

I will try to provide a demo.

Thanks
