### ISSUE TITLE
Update Shell to use Context.VERSION_ES6 by default (instead of Context.VERSION_1_8)

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1279]
Any objections?

**Comment by MaxisTekfield** [comment]
Sounds good.

**Comment by TheRohinth** [comment]
Hi @p-bakker , Greetings for the day.

I look forward for this enhancement of using Context.VERSION_ES6 by default.
When will this be completed ? 
Will this enhancement be delivered in the next version of rhino ?

As I need to use Promises in Rhino-1.7.14
1. I can't just add rhino in dependencies task
2. I need to execute rhino with -version 200 in order to make it support promises
3. but I couldn't configure the -version flag for the same in build.gradle.

I tried to create a task in build.gradle which has the type "JavaExec" that executes the rhino-1.7.14.jar with 
"-version 200" argument. But it did not help.

Do you think this approach would help me ?
If yes, Could you help me with this approach ? 
(if this works out, it will be helpful for me until Context.VERSION_ES6 is made default)

Thanks in advance!
