### ISSUE TITLE
Cannot capture continuation from JavaScript code not called directly by executeScriptWithContinuations or callFunctionWithContinuations

### ISSUE THREAD

**Issue by 821938089** [mozilla/rhino#1444]
I've used executeScriptWithContinuations to call the js code, but it still throws this error.
In testing, I found that continuation cannot be captured in some cases.

```js
function test1 () {
// call a function that capture continuation
}
test1() // success
test1.call() // success
test1.apply(this) // success
(function test1 () {
// call a function that capture continuation
})(); // success

test1.bind(this)() // fail
test1.bind(this).call() // fail

test2 = () => {
// call a function that capture continuation
}
test2() // fail
test2.call() // fail
(() => {
// call a function that capture continuation
})(); // fail


eval('// call a function that capture continuation') // fail

eval(`
function test1 () {
// call a function that capture continuation
}
test1()
`) // fail

eval(`
function test1 () {
// call a function that capture continuation
}
`)() // success

eval(`
function test1 () {
// call a function that capture continuation
}
`).call() // success

eval(`
function test1 () {
// call a function that capture continuation
}
`).apply(this) // success

eval(`
function test1 () {
// call a function that capture continuation
}
`).bind(this)() // fail

eval(`
function test1 () {
// call a function that capture continuation
}
`).bind(this).call() // fail

```

example code that list fail case:

```java

import org.mozilla.javascript.*;

public class Main {

  public static class MyObj {
    public void capture() {
      try (var cx = Context.enter()) {
        throw cx.captureContinuation();
      }
    }
  }

  static Scriptable globalScope;

  public static void main(String[] args) {
    try (var cx = Context.enter()) {
      globalScope = cx.initStandardObjects();
      globalScope.put("myObj", globalScope, Context.javaToJS(new MyObj(), globalScope));
      cx.setOptimizationLevel(-1);

      System.out.println("capture.bind(this)()");
      executeScript(cx, "function capture(){myObj.capture()};capture.bind(this)()");

      System.out.println("capture.bind(this).call()");
      executeScript(cx, "function capture(){myObj.capture()};capture.bind(this).call()");

      System.out.println("[arrow function] capture()");
      executeScript(cx, "capture=()=>{myObj.capture()};capture()");

      System.out.println("[arrow function] capture.call()");
      executeScript(cx, "capture=()=>{myObj.capture()};capture.call()");

      System.out.println("[arrow function] immediate call");
      executeScript(cx, "(()=>{myObj.capture()})();");

      System.out.println("[eval] capture()");
      executeScript(cx, "function capture(){myObj.capture()};eval('capture()')");

    }
  }

  public static void executeScript(Context cx, String script) {
    Script s = cx.compileString(script, "unknown source", 0, null);
    try {
      cx.executeScriptWithContinuations(s, globalScope);
    } catch (ContinuationPending pending) {
      System.out.println("captured!");
    } catch (WrappedException e) {
      System.out.println("capture failed!");
    }
  }

}

```

The reason for this failure is that the call method of the InterpretedFunction class does not inherit from the previous CallFrame, causing outermost.isContinuationsTopFrame to be false.

https://github.com/mozilla/rhino/blob/f48a40d2ca5b3b36f7b353d5edcc3e682f00af29/rhino/src/main/java/org/mozilla/javascript/InterpretedFunction.java#L83-L88

https://github.com/mozilla/rhino/blob/f48a40d2ca5b3b36f7b353d5edcc3e682f00af29/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L1074-L1076

https://github.com/mozilla/rhino/blob/f48a40d2ca5b3b36f7b353d5edcc3e682f00af29/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L3477-L3487

**Comment by p-bakker** [comment]
Don't think this is actionable as it currently stand. 

In order to make it actionable, this issue would have to include a runnable (java) sample, that demonstrates the issue and some analysis of the likely reason of the issue and whether the reason it fails in several scenarios is likely the same or not

**Comment by 821938089** [comment]
@p-bakker Hello, I have updated the comment as per your requirements and I hope this information is useful to you.

**Comment by p-bakker** [comment]
Thnx, that indeed provides a better starting point to understand the issue! 

I doubt there are many devs around that have intricate knowledge of the inner workings of continuations, why they fail in these scenarios, if they can be supported in these scenarios and what is needed to do so... 😐

But who knows... @szegedi: any thoughts maybe? 

Otherwise if you have ideas on how to make this work, a PR is always welcome

There's also case #1475, which is a different scenario in which capturing a Continuation fails

**Comment by szegedi** [comment]
👋 Continuations work as long as all of the execution is contained within a single invocation of `Interpreter.interpretLoop()`. The loop maintains its internal stack for functions, and as long as everything in the call chain is an `InterpretedFunction`, it is supposed to work. Reading the [code](https://github.com/mozilla/rhino/blob/master/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L1725) shows that there's already special handling for `.call()` and `.apply()` so that's why those work.

Bound functions aren't handled specially by the interpreter loop – they could be, though. Just as the special handling for `.call()` and `.apply()` will check if the function they're called on is an interpreted function, the interpreter loop could also check for whether the bound function's underlying function is an interpreted function and install it on its stack directly. This of course leads to a bit of extra complexity. 

Same for arrow functions – I was actually surprised these didn't work out of the box, but I just looked at the code now as I didn't really work much on Rhino since they were introduced and I can see that lambdas are implemented as `ArrowFunction` wrappers around another `Callable`, and not directly as an interpreted function.  We'd need few more "if"s in the call logic in the interpreter and most likely new `initFrameForBoundFunction`, `initFrameForArrowFunction` methods too.

As these things can of course get combined (e.g. you can call apply() on a bound arrow function) to implement this properly, we'd need a generic mechanism for peeling the invoked function in the interpreter back to the interpreted function it ultimately reduces to, and if it does, then walk the chain of functions one more time, invoke all requisite `initFrameForXxx` methods and finally install the function on the stack.

It might actually be simpler to write the code to mark the stack position, then opportunistically start executing all this with the assumption the ultimate function will be an interpreted one, and when it isn't, pop the stack back to the marked position and bail out of the interpreter by invoking `fun.call()` as it is now on [this line](https://github.com/mozilla/rhino/blob/master/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L1896).

**Comment by p-bakker** [comment]
@szegedi Thx a lot for the analysis & input!

@821938089 Think you can roll with all this info and maybe put together a PR?

**Comment by 821938089** [comment]
@p-bakker No, I don't know is what "opportunistically start executing all this" means in the last paragraph.

And I don't know how the interpreter works and I can't be sure if the code I wrote is correct.

**Comment by szegedi** [comment]
I might take a stab at it, it looks like a rather fun task.

**Comment by p-bakker** [comment]
Great @szegedi !

Maybe I'm pushing the envelope a bit, but while at it, could you then also have a look if you see a way to support the usecase described in #1475, which tries to capture a Continuation from Java, but not a Java method called from scripting?

**Comment by szegedi** [comment]
PR ready for review!

**Comment by 821938089** [comment]
Does this pr work in eval? I see the test doesn't have anything about this.

**Comment by szegedi** [comment]
* `eval('function () {c.run()}').bind(this).call()` will work as you'll call the capturing function within a continuation-capturing execution (outside of eval). 
* `var f = function() {c.run()}; eval('f()')` will not work as you'd call the capturing function within a non-capturing execution (inside of eval)

**Comment by 821938089** [comment]
Is it possible to make continuations work in eval?
What it ends up executing is also an InterpreterFunction.

I looked at the source code and found that specific function names can also cause continuations to fail.
This is so surprising.

```java
      System.out.println("eval()");
      executeScript(cx, "function eval(){myObj.capture()};eval()");

      System.out.println("With()");
      executeScript(cx, "function With(){myObj.capture()};With()");
```

**Comment by szegedi** [comment]
Having some names work differently is curious – where in the source code did you look?

And while the functions invoked in eval are interpreted functions, eval itself is not an interpreted function, so when you call eval, you'll step out of the current interpreter loop, hence functions won't work. You'll have on stack:
```
interpreter loop
eval
another interpreter loop
```
I don't expect this will change. At least I'm definitely not inclined to put in the work to make this additional corner case work.

**Comment by 821938089** [comment]
What I've found here is that a function with the name eval or With is assumed to be a special call, and there is a special branch in the interpreter that takes care of it, so it won't jump out of the interpreter loop in that case.

In doCallSpecial the call object is checked to see if it is expected, otherwise it falls back to a normal call, but this normal call will not run in the same interpreter.

https://github.com/mozilla/rhino/blob/d3ebdc5d0ab54c94c3a40abd3dfa00d04d62cd4e/rhino/src/main/java/org/mozilla/javascript/IRFactory.java#L2069-L2091

https://github.com/mozilla/rhino/blob/3581b0268afa65ed7fbfbef0d9039a1035401e06/rhino/src/main/java/org/mozilla/javascript/CodeGenerator.java#L603-L649

https://github.com/mozilla/rhino/blob/3581b0268afa65ed7fbfbef0d9039a1035401e06/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L1737-L1747

https://github.com/mozilla/rhino/blob/3581b0268afa65ed7fbfbef0d9039a1035401e06/rhino/src/main/java/org/mozilla/javascript/Interpreter.java#L2919-L2964

https://github.com/mozilla/rhino/blob/3581b0268afa65ed7fbfbef0d9039a1035401e06/rhino/src/main/java/org/mozilla/javascript/ScriptRuntime.java#L2757-L2780
