### ISSUE TITLE
Discord server for discussion

### ISSUE THREAD

**Issue by gausie** [mozilla/rhino#1474]
Would maintainers be interested in something like a Discord server for discussion of Rhino development?

For context, I'm just running the general compat-table script against 1.7.15 and figured I should mention that somewhere, but an issue didn't seem right.

**Comment by gausie** [comment]
(for info https://github.com/compat-table/compat-table/pull/1891)

**Comment by gausie** [comment]
corejs already did it for us! https://github.com/zloirock/core-js/commit/de8ce566b8096f5674c21fd292d0257ecac65eab#r141817254

**Comment by gbrail** [comment]
If folks in this community want to start a Discord server and put the
details in our GitHub page, I'd be happy to support that, especially if it
means that more people can get engaged with the project. However, for me
personally, I don't have a ton of time and can't promise to stay connected
frequently, so I don't want to set any expectations that I can participate
on a regular basis.

**Comment by p-bakker** [comment]
There's the Discussions area in this repo on GitHub where you can post messages, like that you're working on updating compat table for a new release

Not sure what a Discord server would add to the available options (Discussions on this repo, Google Group) though, except the scattering of info/conversations in more places 

That said, we can always try it out

If you want to go ahead with it, please do and create a PR to include a reference to it in the readme. Otherwise, please close the case
