### ISSUE TITLE
Building version 1.7.16: "No main manifest attribute, in rhino..."

### ISSUE THREAD

**Issue by why-not-try-calmer** [mozilla/rhino#1521]
When running
 
    java -jar rhino/build/libs/rhino-1.7.16-SNAPSHOT.jar  

built with
    
    ./gradlew shadowJar

I am getting 

    no main manifest attribute, in rhino/build/libs/rhino-1.7.16-SNAPSHOT.jar

I am running Java from an Ubuntu WSL-enabled environment on Windows 10:
```
openjdk 11.0.23 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
```

I hope building on WSL 2 is supported...

**Comment by p-bakker** [comment]
@gbrail any thoughts? Likely related to changes for modularizing Rhino?

**Comment by why-not-try-calmer** [comment]
I've managed to reproduce the bug in a widely different environment:

```
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-nixos)
OpenJDK 64-Bit Server VM (build 17.0.7+7-nixos, mixed mode, sharing)
```

**Comment by gbrail** [comment]
Thanks! This is indeed part of the module-based refactoring that we did
recently. "rhino.jar" now contains only the code necessary for the core
Rhino script engine. The "standalone JAR" is now built as rhino-all.jar.
This allows us to add "real" Java module support while requiring build
script changes for the smallest number of people we hope.

You can now launch the stand-alone JAR like this:

java -jar rhino-all/build/libs/rhino-all-1.7.16-SNAPSHOT.jar

("./gradlew build" will build this, as will "./gradlew :rhino-all:build")

I messed up the README update and it does not correctly show this, and I am
testing a PR now so that it correctly shows you how to run the JAR!

Some of the discussions are tracked here:

Adjust module structure for better backward compatibility · Issue #1488 ·
mozilla/rhino (github.com) <https://github.com/mozilla/rhino/issues/1488>
