### ISSUE TITLE
Define "console" object in Rhino Shell

### ISSUE THREAD

**Issue by oswetto** [mozilla/rhino#156]
org.mozilla.javascript.EcmaError: ReferenceError: "console" is not defined.
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4897)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4856)
    at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:5032)
    at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:2272)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1781)
    at script.myFunction(file:/C:/Users/Administrator/Desktop/4.html:3)
    at script.onclick_25774897(button[].onclick:1)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1001)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:151)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:464)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:4041)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:149)

Example:
button onclick="myFunction()"
function myFunction() {
    console.log(1+1);
}

**Comment by gbrail** [comment]
No, it's not part of Rhino or part of JavaScript as far as I know. So it's
not defined in the Rhino shell. What are you trying to do?

On Mon, Mar 9, 2015 at 9:06 AM, Ivan Di Francesco <notifications@github.com>
wrote:

> org.mozilla.javascript.EcmaError: ReferenceError: "console" is not defined.
> at
> org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4897)
> at
> org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4856)
> at
> org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:5032)
> at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:2272)
> at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1781)
> at script.myFunction(file:/C:/Users/Administrator/Desktop/4.html:3)
> at script.onclick_25774897(button[].onclick:1)
> at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1001)
> at
> org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:151)
> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:464)
> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:4041)
> at
> org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:149)
>
> Example:
> Try it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/156>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by oswetto** [comment]
In modern browsers can I write in the console browser (Activate the browser console with F12) using console.log (). Select "Console" in the menu and you can "display" data.

Firefox api: https://developer.mozilla.org/en-US/docs/Web/API/Console

**Comment by gbrail** [comment]
Ah, I get what you're asking -- thanks.

Since Rhino is so tightly embedded into lots of environments, building
"console" into the core might not make sense and could actually cause
problems for some projects that use it. However, the Rhino shell (what
happens when you run Rhino with "java -jar") defines a bunch of additional
functions like "print." It would make sense to add a "console" object in
that context.

I don't know who would have the time to work on that, but if you open up a
GitHub issue with this enhancement there may be someone on this list
interested in taking a crack at implementing it.

On Mon, Mar 9, 2015 at 10:05 AM, Ivan Di Francesco <notifications@github.com
> wrote:

> In modern browsers can I write in the console browser (Activate the
> browser console with F12) using console.log (). Select "Console" in the
> menu and you can "display" data.
>
> Firefox api: https://developer.mozilla.org/en-US/docs/Web/API/Console
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/156#issuecomment-77896441>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by gbrail** [comment]
And as I read my email and GitHub separately I see that this is already an issue. Doh. But thanks!

**Comment by eshepelyuk** [comment]
In our project we implemented `console` class `ConsoleScriptableObject` as a host object using `slf4j` as logging backend.
When creating scope for the script we just inject new propery smth like
````
ScriptableObject.defineProperty(scriptScope, "console", ctx.getContext().newObject(scriptScope, "ConsoleScriptableObject"), READONLY | PERMANENT);
````

So you could try the same.

**Comment by dcitron** [comment]
I just came across this discussion via Google. For anyone else who stumbles upon it, I got this working quite simply with log4j in this way:

``` 
scope.defineProperty(
    "console", 
    Logger.getLogger("theLoggerName"),
    READONLY | PERMANENT);
```

You just need to write expressions like `console.info(...)` then instead of `console.log(...)` unless you want to write an adapter class (unnecessary in my case).
