### ISSUE TITLE
Object Property Order problem

### ISSUE THREAD

**Issue by EnricoScoda** [mozilla/rhino#267]
I know it is not a but but seems that now all major browsers are ordering properties in `for .. in` loops this way:
- first all numeric properties in numeric order
- then the remaining properties using insertion order.

So it looks like they are using the "sorting algorithm" of Arrays for Objects.
If I'm right there are no specs forcing to use an algorithm for Objects but since modern browser use the algorithm I described (V8 started the game?), there is some code out there expecting this order.
Is there a plan to adapt Rhino to the new wave? If I want to make a dirty patch, should I edit getIds of ScriptableObject?

For example the code:
    `test['A'] = 'C';
    test[1] = 'B';
    test[0] = 'A';
    for(var i in test) {
        console.log(test[i]);
    }`
on a modern browser will print A, B and C. Rhino (if a console object is available) will print C, B, A

Note: I used Rhino 1.7.6, I will test on 1.7.7.1 later today.

**Comment by gbrail** [comment]
Yes -- this is required by the ES6 spec.

As part of the work in master to get more ES6 support enabled, we need to
support properties keyed by Symbols as well, and this has been leading me
to work on some big changes to the guts of ScriptableObject, including
ordering of properties on iteration. However I don't have much time to work
on Rhino so it's going a little slowly.

ES6, section 9.1.12 if I am reading it correctly, actually does specify
this:

...

When the [[OwnPropertyKeys]] internal method of O is called the following
steps are taken:
Let keys be a new empty List.
For each own property key P of O that is an integer index, in ascending
numeric index order
Add P as the last element of keys.
For each own property key P of O that is a String but is not an integer
index, in property creation order
Add P as the last element of keys.
For each own property key P of O that is a Symbol, in property creation
order
Add P as the last element of keys.
Return keys.

On Tue, Feb 9, 2016 at 10:27 AM, EnricoScoda <notifications@github.com>
wrote:

> I know it is not a but but seems that now all major browsers are ordering
> properties in for .. in loops this way:
>
>    - first all numeric properties in numeric order
>    - then the remaining properties using insertion order.
>
> So it looks like they are using the "sorting algorithm" of Arrays for
> Objects.
> If I'm right there are no specs forcing to use an algorithm for Objects
> but since modern browser use the algorithm I described (V8 started the
> game?), there is some code out there expecting this order.
> Is there a plan to adapt Rhino to the new wave? If I want to make a dirty
> patch, should I edit getIds of ScriptableObject?
>
> For example the code:
> test['A'] = 'C';
> test[1] = 'B';
> test[0] = 'A';
> for(var i in test) {
> console.log(test[i]);
> }
> on a modern browser will print A, B and C. Rhino (if a console object is
> available) will print C, B, A
>
> Note: I used Rhino 1.7.6, I will test on 1.7.7.1 later today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/267>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by gbrail** [comment]
Belated issue update:

This is fixed in master. If the language version is >= "VERSION_ES6" then the various iterators will iterate in the spec-required order:

First all numeric-keyed properties, in numeric order
Second all string-keyed properties, in insertion time order
And soon all Symbol-keyed properties, in insertion time order

I upgraded our micro-benchmarking framework for this one and ran a lot of micro benchmarks using Google Caliper. The solution that had the least impact on the performance of Rhino overall in these benchmarks was to sort the array once it's been constructed. The "Arrays.sort" code in Java is quite clever and results in a stable sort, so it's efficient and the code change was very small.

I considered other options and even tried a few, including replacing the complex code to manage "slots" for objects with regular old HashMap and LinkedHashMap instances, and it turned out that all those attempts are slower than the hand-rolled code that various people contributed a decade ago. So sorting it is.

I hope to add proper Symbol support soon, then we will have a platform where we can add more ES6 features if others have time. I hope that they do!
