### ISSUE TITLE
How to add class?

### ISSUE THREAD

**Issue by nabeghe** [mozilla/rhino#273]
hi
i wana to add class and then creat new object from that class in javascript
how do this?

thanks

**Comment by gbrail** [comment]
I'm not sure I know quite what you're asking.

Rhino is one of many ways to run JavaScript. It's actually one of the
oldest implementations, and continues to find a home because it's very
flexible and can be embedded into many different products that are built in
Java. However, it's only one option.

There are many great on-line resources for learning JavaScript. Maybe that
would be a good place to start?

On Wed, Feb 24, 2016 at 2:40 PM, nabeghe <notifications@github.com> wrote:

> hi
> i wana to add class and then new in javascript
> how do this?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/273>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by gbrail** [comment]
Unless there's a specific request or problem here then I'm going to close this as a GitHub issue. Let us know, preferably on the Google Group / email list, if you have more questions:

https://groups.google.com/forum/#!forum/mozilla-rhino
