### ISSUE TITLE
Speed up JS compilation 

### ISSUE THREAD

**Issue by CaledoniaProject** [mozilla/rhino#380]
Hi there, I'm using Rhino engine in [OpenRASP project](https://github.com/baidu/openrasp)

During startup, it takes 7 seconds to compile the javascript stub code.

```
            name = "shim.js";
            is = Object.class.getResourceAsStream("/" + name);
            script = IOUtils.toString(is, "UTF-8");
            cx.evaluateString(globalScope, script, name, 1, null);
            name = "console.js";
            is = Object.class.getResourceAsStream("/" + name);
            script = IOUtils.toString(is, "UTF-8");
            cx.evaluateString(globalScope, script, name, 1, null);
            name = "error.js";
            is = Object.class.getResourceAsStream("/environment/" + name);
            script = IOUtils.toString(is, "UTF-8");
            cx.evaluateString(globalScope, script, name, 1, null);
            name = "checkpoint.js";
            is = Object.class.getResourceAsStream("/environment/" + name);
            script = IOUtils.toString(is, "UTF-8");
            cx.evaluateString(globalScope, script, name, 1, null);
            name = "rasp.js";
            is = Object.class.getResourceAsStream("/environment/" + name);
            script = IOUtils.toString(is, "UTF-8");
            cx.evaluateString(globalScope, script, name, 1, null);
```

I'm wondering if there's any way to speed things up? 

Perhaps one should store the compiled object on disk, and load them on startup?

**Comment by gbrail** [comment]
You can certainly pre-compile stuff -- it's absolutely a good idea if you
have code that you are going to execute over and over again, since by
default "evaluateString" first compiles to bytecode and then executes that
(and then let's the bytecode get GCed). You can do this in various ways,
either in your code using the various "compile*" methods on the Context,
class, or using the "jsc" tool as described on this very old (but still
useful) web page:

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/JavaScript_Compiler

However, seven seconds for a compilation sounds incredibly long for me.
Trireme, which I built a few years ago on top of Rhino, runs Node.js apps,
which typically load and compile tens or hundreds of thousands of lines of
JavaScript before they can accept a single request, and they rarely take
that long to start.

Have you tried any kind of profiling to see where the problem might be?

**Comment by CaledoniaProject** [comment]
Looks good, it now takes roughly 1s to load the javascript code now.
