### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by havrikov** [mozilla/rhino#385]
When evaluating the attached file , an `IllegalStateException` is thrown.
[rhino_ise.zip](https://github.com/mozilla/rhino/files/1691899/rhino_ise.zip)
Rhino version: `1.7.7.2`
Kotlin code to reproduce the issue if `path` points to the attached file:
```
File(path).reader().use {
            val context = Context.enter()
            val scope = context.initStandardObjects()
            context.evaluateReader(scope, it, path, 1, null)
        }
```

**Comment by sainaen** [comment]
Thanks for reporting!

Here’s the slightly reduced source code that still reproduces the problem:
```js
var { a: {} = 'b' } = {};
```

Basically, because Rhino doesn’t currently support [default values inside destructing](http://exploringjs.com/es6/ch_destructuring.html#sec_default-values-destructuring), this code is parsed correctly but causes problems down the line.

Here’s how Rhino parses it:
```
0	SCRIPT 0 25
0	  VAR 0 25
4	    VAR 4 20
4	      OBJECTLIT 0 15
6	        COLON 2 11
6	          NAME 0 1 a
9	          ASSIGN 3 8 << we don't expected assignment here
9	            OBJECTLIT 0 2
14	            STRING 5 3
22	      OBJECTLIT 18 2
```

This is a legal expansion:

```
// skipping some intermediate steps
var VariableDeclaration ;
var ObjectBindingPattern Initializer ;
var { BindingProperty } Initializer ;
var { LiteralPropertyName : BindingElement } Initializer ;
var { a : BindingElement } Initializer ; // replaced LiteralPropertyName with the actual value
var { a : BindingPattern Initializer[opt] } Initializer ;
var { a : ObjectBindingPattern Initializer[opt] } Initializer ;
var { a : {} Initializer[opt] } Initializer ;
var { a : {} = AssignmentExpression } Initializer ;
var { a : {} = 'b' } Initializer ;
var { a : {} = 'b' } = AssignmentExpression ;
var { a : {} = 'b' } = {} ;
```

But when `IRFactory`’s [`decompileObjectLiteral()`](https://github.com/mozilla/rhino/blob/6f0f1f669ed3da8a476af736c97ab41ba32873cc/src/org/mozilla/javascript/IRFactory.java#L2428-L2446) passes right-hand side, which is the `{} = 'b'` part with a type `Token.ASSIGN`,  to [`decompile()`](https://github.com/mozilla/rhino/blob/6f0f1f669ed3da8a476af736c97ab41ba32873cc/src/org/mozilla/javascript/IRFactory.java#L2378-L2410), the latter does not know how to handle that and throws.

**Comment by sainaen** [comment]
I’ll think about this more on Monday, but right now I’m inclined to just report an error in the `Parser` when we see default value used, with a proper message of course, until we actually implement this.

**Comment by sainaen** [comment]
Adding an error reporting to parser doesn’t seem to be hard:
```diff
@@ -2253,6 +2253,10 @@ public class Parser
             tt = peekToken();
         }
         if (Token.FIRST_ASSIGN <= tt && tt <= Token.LAST_ASSIGN) {
+            if (inDestructuringAssignment) {
+                reportError("msg.destruct.default.vals");
+            }
+
             consumeToken();
```

This change doesn’t break any of the existing tests.

I was worried if any of the `Parser` users rely on it being able to parse cases like `var {a = 10} = b`, even if Rhino itself can’t execute them. Destructuring assignments were supported here for so long (since 2009) this _bug_/_feature_ could’ve been adopted in the unexpected use cases.
But it turns out it’s a very limited implementation to rely on — we can’t even parse correctly the basic case `var {a = 10} = b`! (long-form `var {a: a = 10} = b` works, though) So I’d say it’s safe to add this check.

Also, I don’t think it should be restricted to `languageVersion >= ES6` since destructuring is not limited to ES6.

**Comment by sainaen** [comment]
I’ve opened a PR #389 with a fix.
