### ISSUE TITLE
A Kun has plagued me for a long time

### ISSUE THREAD

**Issue by YanLingHao** [mozilla/rhino#387]
I was calling this method for the first time. Function function = (Function) scope.get(functionName, scope);. Return to the result type is Object .I call this method at the second time. Function function = (Function) scope.get(functionName, scope);. Return to the result type is UniqueTag？Cause second invocation exceptions.

**Comment by sainaen** [comment]
Assuming `scope` is an instance of `Scriptable`, its `get(String, Scriptable)` returns either:
* `java.lang.Boolean` objects
* `java.lang.String` objects
* `java.lang.Number` objects
* `org.mozilla.javascript.Scriptable` objects
* `null`
* the value returned by `Context.getUndefinedValue()`
* `Scriptable.NOT_FOUND`

The last one, `Scriptable.NOT_FOUND`, which is an instance of `UniqueTag`, is returned from `get()` when requested property is not found.

Are you sure that the property you’re asking for is present in `scope`? What does `scope.has(functionName, scope)` return in the second case?

**Comment by YanLingHao** [comment]
I first call 
NativeObject resultep = (NativeObject) runScript(bufferedReader, "gt_ep", new Object[]{}, mContext);
Post call
NativeArray resultpow = (NativeArray) runScript(bufferedReader, "gt_w", new Object[]{a, b, c}, mContext);
Exceptions called after discovery
 
runScript Method
  public Object runScript(Reader js, String functionName, Object[] functionParams, Context context) {
        org.mozilla.javascript.Context rhino = org.mozilla.javascript.Context.enter();
        rhino.setLanguageVersion(org.mozilla.javascript.Context.VERSION_1_8);
        rhino.setOptimizationLevel(-1);
        try {
            Scriptable scope = rhino.initStandardObjects();
            ScriptableObject.putProperty(scope, "javaContext", org.mozilla.javascript.Context.javaToJS(context, scope));
            ScriptableObject.putProperty(scope, "javaLoader", org.mozilla.javascript.Context.javaToJS(context.getClassLoader(), scope));
            try {
                rhino.evaluateReader(scope, js, "NewActivity", 0, null);
            } catch (IOException e) {
                e.printStackTrace();
            }
            Function function = (Function) scope.get(functionName, scope);
            Object result = function.call(rhino, scope, scope, functionParams);
            return result;
        }catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        finally {
            org.mozilla.javascript.Context.exit();
        }
    }

 Function function = (Function) scope.get(functionName, scope);This line is UniqueTag error.

Trouble you to see the reason.

**Comment by sainaen** [comment]
Right, so the `scope` _is_ `Scriptable`.

So, I have two guesses:

1. Your script just doesn’t define `gt_w` function in the global scope, so that’s why you get `NOT_FOUND` from `scope.get("gt_w", scope)`

  To fix this, you need to make sure that the script you’re executing actually defines functions you expect it to define.

2. Since Rhino doesn’t reset the reader it gets, if you pass the same `bufferedReader` twice `evaluateReader()` will find that it can’t read anything and assume that it’s just an empty file

If this is the case, you need to either call `reset()` on your `bufferedReader` (note, that not all `Reader`s support that!) after the first `runScript()`, or rewrite your code in the way that will call `evaluteReader()` only once for a given reader.

**Comment by p-bakker** [comment]
Closing this as the previous comment seems to contain the answer to your problem.

If you think you're still experiencing a bug in Rhino, feel free to reopen this issue
