### ISSUE TITLE
Java code formatter

### ISSUE THREAD

**Issue by tuchida** [mozilla/rhino#863]
I would like a code formatter to unify coding styles.
- Use gradle to check and format (for example: `./gradlew format`)
- (Optional) Checking with CI
- (Optional) Integration with editors

Is this a good idea to use?
https://github.com/sherter/google-java-format-gradle-plugin

**Comment by tuchida** [comment]
They are still using Checkstyle to check the coding style.
https://github.com/mozilla/rhino/blob/9ebcb56b7461b01d809c40a281db3c75f43f20d7/checkstyle.xml
```sh
./gradlew check
```
However, Checkstyle did not seem to have an autofix feature.

> https://github.com/sherter/google-java-format-gradle-plugin

I tried to use this plugin, but I couldn't figure out where the syntax error was.

I tried this.
https://github.com/diffplug/spotless/tree/main/plugin-gradle#google-java-format

```diff
diff --git a/build.gradle b/build.gradle
index 249b1a49..019af96d 100644
--- a/build.gradle
+++ b/build.gradle
@@ -8,6 +8,7 @@ plugins {
     id 'distribution'
     id 'checkstyle'
     id 'com.github.spotbugs' version "4.6.2"
+    id "com.diffplug.spotless" version "5.12.1"
 }
 
 tasks.withType(JavaCompile) {
@@ -25,6 +26,12 @@ repositories {
     mavenCentral()
 }
 
+spotless {
+    java {
+        googleJavaFormat('1.7').aosp()
+    }
+}
+
 sourceSets {
     main {
         java {
```
```sh
# check
$ ./gradlew spotlessCheck

# autofix
$ ./gradlew spotlessApply
```
There was a very large amount of revision.

**Comment by gbrail** [comment]
As you figured out, checkstyle is already in the build but except for some very obvious rules it's mostly turned off. It's no issue at all to adjust the checkstyle rules to enforce more things, or to replace it with another formatter.

The problem is that adopting any formatter would introduce a multi-thousand-line set of changes to the codebase. Everyone who has an outstanding PR, or a branch with a bit of experimental things, or a fork of Rhino, would have a messy merge on their hands.

I can think of a few ways to make this less painful:

1) Introduce rules a few at a time using checkstyle, so that there are only a few hundred thousand changes at once rather than tens of thousands
2) Agree on some sort of "moratorium" time after which everyone with an outstanding PR is going to be expected to merge all the formatting changes and resolve all the conflicts.

But I have held off on doing anything like this because of the aforementioned merge problems.

If there were some code formatter out there that we could annotate with "already fixed" or something so that it'd only complain about certain files, then perhaps that would be another way.

**Comment by rbri** [comment]
At least in teamcity there is a way to have some kind of dynamic threshold like ,The number of warnings of a build has to be <= the number of the previous build. Maybe enabling something like this for the ci build might be a way into a future with more consistent formatting. 

Am 13. April 2021 18:54:50 MESZ schrieb Greg Brail ***@***.***>:
>As you figured out, checkstyle is already in the build but except for
>some very obvious rules it's mostly turned off. It's no issue at all to
>adjust the checkstyle rules to enforce more things, or to replace it
>with another formatter.
>
>The problem is that adopting any formatter would introduce a
>multi-thousand-line set of changes to the codebase. Everyone who has an
>outstanding PR, or a branch with a bit of experimental things, or a
>fork of Rhino, would have a messy merge on their hands.
>
>I can think of a few ways to make this less painful:
>
>1) Introduce rules a few at a time using checkstyle, so that there are
>only a few hundred thousand changes at once rather than tens of
>thousands
>2) Agree on some sort of "moratorium" time after which everyone with an
>outstanding PR is going to be expected to merge all the formatting
>changes and resolve all the conflicts.
>
>But I have held off on doing anything like this because of the
>aforementioned merge problems.
>
>If there were some code formatter out there that we could annotate with
>"already fixed" or something so that it'd only complain about certain
>files, then perhaps that would be another way.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/rhino/issues/863#issuecomment-818890415

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tuchida** [comment]
> I can think of a few ways to make this less painful:

If you have the auto-formatting feature, you can simply run the command to remove the error.
If it were only a check feature, it would take an effort to correct even a minor rule change.

**Comment by gbrail** [comment]
This may not be as bad as I had feared, since spotless has the "ratchet" feature. Check out https://github.com/mozilla/rhino/pull/866 and if you like it we'll do it!

**Comment by rbri** [comment]
Fine for me +1

**Comment by tuchida** [comment]
Thanks!
