### ISSUE TITLE
About converting java annotations to javascript code

### ISSUE THREAD

**Issue by yizhiyan** [mozilla/rhino#871]
When using webview in a JavaScript environment, I need to use `webViewWidget.addJavascriptInterface` to expand the interface of webview, but the `android.webkit.JavascriptInterface` interface must expose methods in java. It must be annotated with `@JavascriptInterface`

I am very confused, how to use rhino's javascript environment to achieve

I have tried to use `JavaAdapter` to achieve it, but unfortunately it was not successful

**Comment by p-bakker** [comment]
Rhino doesn't support adding Java Annotations to JavaScript methods that make up the methods of a Java Class implemented in JavaScript through for example the JavaAdapter.

Based on a quick Google maybe you can use the lower API level that doesn't require the annotation or maybe it works if you implement a base class or interface in Java with those annotations and the extends that class/interface in JavaScript. Not sure if that would work, but that's what I'd try. Otherwise I think you're out of luck on this one

Closing this case now, feel free to reopen if you think something is amiss in Rhino
