### ISSUE TITLE
Comparing a java.lang.String with a JavaScript string doesn't work in switch statements

### ISSUE THREAD

**Issue by jabortell** [mozilla/rhino#891]
It appears that comparing a `java.lang.String` with a JavaScript `string` doesn't work in `switch` statements. In the code below, only the `print` in the if-statement fires. I tested this using the latest released version of rhino, 1.7.13

```javascript
js_string = "hello world"
java_string = java.lang.String("hello world")

if (js_string == java_string) {
    print("JS string == Java string works in an if-statement")
}

switch (java_string) {
    case js_string:
        print("Switching on the Java String, comparing to JS String, works.")
        break;
}

switch (js_string) {
    case java_string:
        print("Switching on the JS string, comparing to Java String, works.")
        break;
}
```

**Comment by tonygermano** [comment]
That is correct. That's because a switch uses strict equality (same as `===` comparison operator.)  You'd get the same result in any javascript environment if you did
```js
java_string = new String("hello world")
```
In either example, `typeof java_string` returns "object", which means it can't be strictly equal to `js_string`, which is a string.

If you would like to use a java string source in a switch statement, this will convert it to a javascript string primitive.
```js
java_string = String(java.lang.String("hello world"))
```

**Comment by tonygermano** [comment]
@jabortell Can you please close this issue if it is resolved?
