### ISSUE TITLE
Release 1.7.14

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#966]
Placeholder for the work to release the next iteration of Rhino: v1.7.14

We're at least waiting for Promise to land (https://github.com/mozilla/rhino/issues/160)

Any other things we want to get done before finalizing v1.7.14?

With our next release after v1.7.14 probably coming after the release of Java 17 (due), I wonder if we should tackle [Illegal Reflective Operation](https://github.com/mozilla/rhino/issues/462) as Java 17 is going to be more restrictive again on these type of operations

**Comment by p-bakker** [comment]
Personally I'd love to move the bar on Test262 coverage a bit, hopefully so we can at least update to the latest commit on test262 main branch.

This would entail at least fixing/implementing the things that are used by the test262 harness code (see label [`test262 harness`](https://github.com/mozilla/rhino/labels/test262%20harness), so we don't have failing tests just because the harness uses syntax we don't support yet

**Comment by gbrail** [comment]
I think that we should complete Promises and also tackle the illegal
reflective operations. We've discussed before and I believe that this
version of Rhino still needs to build and run with Java 8. That means the
solution for the reflective operations needs to be itself done with
reflection, by creating a new instance of the "vmbridge" classes for Java
9+. I believe that the solution is otherwise in an issue here somewhere.

After that, I think that we need two weeks or so of "rampdown" time in
which we don't add new features but instead only fix bugs and add tests,
and during that time everyone can test the new release with their various
projects.

**Comment by p-bakker** [comment]
Issue about the illegal reflective operations: https://github.com/mozilla/rhino/issues/462

**Comment by gausie** [comment]
Is there any existing discussion about moving to semantic versioning for the Rhino package? It would be nice in general, but also fitting for a JS engine

**Comment by botic** [comment]
> After that, I think that we need two weeks or so of "rampdown" time in which we don't add new features but instead only fix bugs and add tests, and during that time everyone can test the new release with their various projects.

As soon as you announce a release candidate, I'll try it out in RingoJS. Good to hear Promise support should land in Rhino, since we have to fiddle around with a Ringo-only Promise implementation and this turned out to be unpractical.

**Comment by p-bakker** [comment]
> Is there any existing discussion about moving to semantic versioning for the Rhino package?

Not directly, as far as I'm aware of.

But I have now mentioned it in our our first discussion:  https://github.com/mozilla/rhino/discussions/972

**Comment by p-bakker** [comment]
We might want to resolve other issues labels with [distribution](https://github.com/mozilla/rhino/labels/distribution) with this release as well

**Comment by tonygermano** [comment]
Just wanted to throw out my opinion that we're ready for a 1.7.14 release. There's been a significant amount of change since 1.7.13, and 1.7.15 can always be a smaller and faster release if there are any lingering things we wanted to include in 1.7.14 that aren't ready yet.

**Comment by SuperPat45** [comment]
The problem with the IllegalAccessException thrown since Java 17 (only warn in Java 11), described in #462, makes it unusable for me.

**Comment by p-bakker** [comment]
I've assigned a few open issues to the [1.7.14 milestone](https://github.com/mozilla/rhino/milestone/14) as I think they ought to be resolved before 1.7.14 can be released.

In addition to the issues/pr's assigned to the milestone, I wonder if the bytecode issue of #915 should also not get tackled before the 1.7.14 release.

Same for the nullPointers mentioned in #988

And maybe look at at least all recently created open PR's (id > 1000 for example) to see if they can be wrapped up and included

**Comment by tonygermano** [comment]
https://github.com/mozilla/rhino/compare/Rhino1_7_13_Release...master

1.7.13 was released over a year ago. At present time there have been 302 commits and 274 files changed since then. It's got some big features like template literals that people have been waiting on for years.

I don't see a reason to wait. The issues in the milestone are complex problems, and none of them are critical to people already running an earlier release. They either affect new features that didn't exist in 1.7.13 or new java versions that don't matter to people that aren't running bleeding edge java. Put everything currently in the 1.7.14 milestone to 1.7.15, and release that as soon as they're finished (which might take a while!) We can call it 1.7.14.1 if that would help.

**Comment by gbrail** [comment]
Yes -- there are a few things in the queue but they can be resolved.

The main problem is that I did all the recent releases and I haven't been
able to find any time for Rhino at all recently.

However, pushing out the release takes only an hour or so. What takes
longer is putting together the release notes, which for this release will
be big because we have a few new features, especially regarding Java
interop that:

   - Were split across many commits so the commit log is not a good way to
   see what went on
   - Had significant discussion outside the commit log
   - Are more than just "implement well-documented JavaScript standard X"

If I start a release by creating a branch and forking off the release
notes, are there any volunteers to iterate on the release notes themselves,
or even other updated docs since the Mozilla site went away? If we all wait
for me it will be some time yet I am afraid.

**Comment by gbrail** [comment]
Let's just tag them in the milestone. My point is that we need to stop
merging somewhere and give everyone a week or two with a release candidate
before we do an actual release.

As for some of the other open issues that don't have fixes:

https://github.com/mozilla/rhino/issues/915 -- this has been in there for
many releases and although I agree it should be fixed, I also don't know
who is going to fix it and I don't think we should hold up the release as
it's not a new regression.

https://github.com/mozilla/rhino/issues/988 -- this one is worth looking
at, but I'm not sure again who will be able to do that and how long we
should hold up a potential release.

**Comment by p-bakker** [comment]
Added #915 and #988 to the [1.7.14](https://github.com/mozilla/rhino/milestone/14) milestone

Also started going through all the merged PR's since the 1.7.13 release and linking either the PR or it's linked cases to the [1.7.14](https://github.com/mozilla/rhino/milestone/14) milestone, as a starting point for the Release Notes

**Comment by p-bakker** [comment]
Also created a Wiki page to collaborate on the Release Notes: https://github.com/mozilla/rhino/wiki/DRAFT:-Rhino-1.7.14-Release-Notes

**Comment by carlosame** [comment]
> PR #1040 claims to resolve it (among other things). Anyone in the position to review that PR?

I added a [post with a summary of what's being fixed](https://github.com/mozilla/rhino/pull/1040#issuecomment-942350486), to help potential reviewers.

That post mentions the possibility of using the [ASM library](https://asm.ow2.io/) in the future, and is worth mentioning it here because it may have implications for other issues. If ASM became a dependency of Rhino, it could be used across the `org.mozilla.classfile` package and perhaps one no longer would need to care about problems like #915. BTW that would be more appropriate for a 1.8.0 than a 1.7.x.

My point is that a full fix of illegal reflective accesses (I mean other than the type of error mentioned in #462 which is fixed by my PR) has implications for at least #915 and IMHO both could be left out for a future 1.8.0.

Otherwise the release of 1.7.14 could be delayed indefinitely or at least well into 2022.

**Comment by tonygermano** [comment]
@carlosame What would the implications be for running on Android if ASM were a dependency?

**Comment by tonygermano** [comment]
@p-bakker I like the way you have it organized better, but it still might be nice to add the attribution next to the issue/PR description?

**Comment by p-bakker** [comment]
Just to keep track of things: might have to do some stuff for the Kangax Compat Table to be based on the new release, once released: https://github.com/mozilla/rhino/issues/661

**Comment by carlosame** [comment]
> There are other ByteCode generation libraries out there that support both both regular Java and Dalvik, like Byte buddy.

My understanding is that the other bytecode management libraries are just font-ends to ASM, certainly Byte Buddy depends on it. From their homepage:
> "Byte Buddy is a light-weight library and only depends on the visitor API of the Java byte code parser library ASM which does itself not require any further dependencies."

In any case, they also need to access the bytecode (and hence the class file which isn't a thing in Android), although I guess that one could still generate bytecode "on the fly" and then load that bytecode in order to run it. Not sure how/if that would work on Android though.

**Comment by carlosame** [comment]
> Not sure how/if that would work on Android though.

ASM cannot be used at all on Android, they started a project called [ASMDEX](https://gitlab.ow2.org/asm/asmdex) aimed at it but is now archived.

I found [Soot](http://soot-oss.github.io/soot/) which can instrument both JVM and Android bytecodes, although seems more complex to use than ASM. The [Creating a class from scratch](https://github.com/soot-oss/soot/wiki/Creating-a-class-from-scratch) tutorial is informative, and the tutorials listed in [Using Soot as a compiler framework](https://github.com/soot-oss/soot/wiki/Tutorials#using-soot-as-a-compiler-framework) seem relevant.

The [Instrumenting Android Apps with Soot](https://github.com/soot-oss/soot/wiki/Instrumenting-Android-Apps-with-Soot) wiki page describes the usage on that platform, but one would have to detect the Android environment first (perhaps checking for `java.vm.name` or `java.runtime.name`), then initialise Soot accordingly.

**Comment by p-bakker** [comment]
Maybe move this byte code discussion to an actual discussion? Think its off topic for the v1.7.14 release

**Comment by p-bakker** [comment]
@tuchida @rPraml @tonygermano 
Could you check the Java Interop section of the draft release notes whether they are complete and correct? 

Tried my best to compile that list based on the changes in the [relevant PRs](https://github.com/mozilla/rhino/issues?q=label%3A%22Java+Interop%22+milestone%3A%22Release+1.7.14%22), but I might have missed or wrongfully interpreted something

**Comment by tuchida** [comment]
> #1031 .delete() and .length setting support in JavaScript on Java Lists

It is `delete` operator, not `.delete()` method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

**Comment by p-bakker** [comment]
> It is delete operator, not .delete() method.
Tnx, corrected

**Comment by gbrail** [comment]
These are great -- thanks! I do like the idea of adding GitHub IDs of
contributors. If that's a ton of work or doesn't make sense, then another
thing we can do is when done, pull together a note about how many people
worked on this release (I can easily get that from GH commit history and
will do it with the release.)

I'd like to create a release candidate early next week -- I usually put
what you have here in markdown format at the start of RELEASE-NOTES.md. Let
me know if you're OK with that, and either create a "prepare release notes
for 1.7.14" PR or I'll do it next week.

**Comment by p-bakker** [comment]
> If that's a ton of work or doesn't make sense

Its not a ton of work, just something to be done. Any volunteers?

>  pull together a note about how many people worked on this release

I'd add that to the release notes regardless

> I usually put what you have here in markdown format at the start of RELEASE-NOTES.md. Let me know if you're OK with that

While that is fine by me, I wonder what the purpose of RELEASE-NOTES.md is: Why not just add the notes to the actual release entry under Releases in GitHub? That was at least my intention for the draft wiki page: to basically copy/paste that into the description of the release once the release got created

**Comment by gbrail** [comment]
I am likely old-fashioned, but I like having the important stuff in the project all be part of the actual repo that everyone pulls down, and not on a wiki that stores its data somewhere else. So I think it's important that we continue the tradition of keeping a RELEASE_NOTES file in the repo itself.

**Comment by wetneb** [comment]
Thank you all for your work towards this release! We are eagerly awaiting it in [OpenRefine](https://github.com/OpenRefine/OpenRefine) for the Java 16 compatibility.

**Comment by p-bakker** [comment]
See https://github.com/mozilla/rhino/discussions/1088, RC1 is here!

**Comment by p-bakker** [comment]
Closing this case, as RC1 is here. Any furhter dicussion can take place on #1088 

@tonygermano tnx for adding the involved committers to the release notes! Hadn't noticed it before
